config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home'

  get 'pages/about', to: 'pages#about'

  get 'pages/contact', to: 'pages#contact'

  get 'pages/booking', to: 'pages#booking'
  
  get 'pages/photo', to: 'pages#photo'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def booking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabin</title>
    <%= render 'shared/nav' %>
    <%= render "shared/footer" %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="wite-wrapper-inner">
        <div class="cover-container">
        </div>
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/booking.html.erb
<div class='container-fluid'>
  <h1 class='title'>Booking Info</h1>
  <div class='card'>
    <p>For more details and booking info, click here <%= link_to "VRBO", "https://www.vrbo.com/76410", :target => "_blank" %></p>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="card home-card"
  <p>
    This is one of the finest homes in the Sundance Resort area. It is located less than one mile from the ski lifts, thus making it very accessible to the activities of the resort, yet far enough away to give you the privacy and quietness one would expect in the beautiful Rocky Mountains. Truly, a place to build memories that will last a lifetime.
  </p>
  <p>
   We are located just minutes away from the Provo river, known for its great brown trout fishing. Park City is a fun town just a short 25 minute drive where you can find more skiing, the alpine slide (summer), hiking, biking, golfing, and great restaurants. Outlet stores there are open year round. This was home for the 2002 Olympic ski jumping the luge events. Wasatch State Park located just minutes from Heber City is beautiful in summer and has gorgeous golf courses, it also is a great place to go snowmobiling in the winter. This will be the home for the cross country ski event. Click below to see availible dates and additional information on the property.
  </p>

<p><%= link_to "Booking Details", "https://www.vrbo.com/76410", class: "vrbo-btn btn btn-lg btn-primary" %></p>

  </div>  

<%= render 'shared/carousel' %>

<%= link_to "All photos", pages_photo_path, class: "photo-btn btn btn-lg btn-primary" %></p>


</div>

app/views/shared/_carousel.html.erb
<div class='container-fluid'>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100"<%= image_tag "cabin.jpg", width: 100, alt: "profile image", class: 'profile-img' %> 
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin2.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin3.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin4.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin5.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin7.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin9.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100"<%= image_tag "cabin11.jpg", width: 100, alt: "profile image", class: 'profile-img' %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
    <div class="container-fluid">
      <div class="footer-content">
        <ul class="footer-block">
        <ul>Website created by Brett Lorscheider</ul>
        <ul><%= link_to "www.brettlorscheider.com", "http://www.brettlorscheider.com", :target => "_blank" %></ul>
        <ul><a href="mailto:brettlorsch@gmail.com">Email Me</a></ul>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #00b36b;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Photos", pages_photo_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Booking", href='https://www.vrbo.com/76410' %>
      </li>
    </ul>
  </div>
</nav>
<div>
  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  <h1 class="title">Sundance Luxury Cabin</h1>
</div>